sudo: required

language: generic

services:
  - docker

before_script:
  - docker-compose build

script:
 - docker-compose run -e CODECOV_TOKEN=$CODECOV_TOKEN --rm auth_app bash -c "make run-ci"

after_script:
  - docker-compose down

notifications:
  email: false
