FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN pip3.6 install pipenv

COPY . code
WORKDIR /code
RUN pipenv install --system --dev
EXPOSE 5555

CMD cd auth && flower --app auth --port=5555 --basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}
